[package]
name = "menser"
authors = ["FlareFlo"]
description = "Fetches and displays meals from the stw-on API"
documentation = "https://docs.rs/menser"
repository = "https://github.com/FlareFlo/menser"
version = "0.1.4"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.7"
futures = { version = "0.3.28", default-features = false, features = ["executor"]}
reqwest = { version = "0.11.18", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false}
serde_with = { version = "3.0.0", default-features = false, features = ["macros"]}
tokio = { version = "1.29.1",  default-features = false, features = ["macros", "rt-multi-thread"] }
